export const SERVICES = [
  { id: 'shampoo', label: 'Shampoo', category: 'Cabelo / Cortes / Brushing', price: '2€' },
  { id: 'amaciador', label: 'Amaciador', category: 'Cabelo / Cortes / Brushing', price: '3€' },
  { id: 'mascara', label: 'Máscara', category: 'Cabelo / Cortes / Brushing', price: '4,50€' },
  { id: 'protetor_tecnico', label: 'Protetor técnico', category: 'Cabelo / Cortes / Brushing', price: '6€' },
  { id: 'espuma_cor', label: 'Espuma cor', category: 'Cabelo / Cortes / Brushing', price: '6€' },
  { id: 'serum_reparador', label: 'Sérum reparador', category: 'Cabelo / Cortes / Brushing', price: '6€' },
  { id: 'espuma_orbital', label: 'Espuma orbital', category: 'Cabelo / Cortes / Brushing', price: '5€' },
  { id: 'corte', label: 'Corte', category: 'Cabelo / Cortes / Brushing', price: '10€' },
  { id: 'corte_crianca', label: 'Corte criança', category: 'Cabelo / Cortes / Brushing', price: '6€/9€' },
  { id: 'corte_jovem_brushing', label: 'Corte jovem + brushing', category: 'Cabelo / Cortes / Brushing', price: '20€' },
  { id: 'brushing_curto', label: 'Brushing curto', category: 'Cabelo / Cortes / Brushing', price: '8€' },
  { id: 'brushing_medio', label: 'Brushing médio', category: 'Cabelo / Cortes / Brushing', price: '9€' },
  { id: 'brushing_medio_longo', label: 'Brushing méd. longo', category: 'Cabelo / Cortes / Brushing', price: '12€' },
  { id: 'brushing_comprido', label: 'Brushing comprido', category: 'Cabelo / Cortes / Brushing', price: '15€' },
  { id: 'prancha', label: 'Prancha', category: 'Cabelo / Cortes / Brushing', price: '15€' },
  { id: 'prancha_jovem', label: 'Prancha jovem', category: 'Cabelo / Cortes / Brushing', price: '12€' },
  { id: 'penteado_especial', label: 'Penteado especial', category: 'Cabelo / Cortes / Brushing', price: 'sob consulta' },

  { id: 'coloracao_curto', label: 'Coloração curto', category: 'Coloração', price: '34€' },
  { id: 'coloracao_medio', label: 'Coloração médio', category: 'Coloração', price: '36€' },
  { id: 'coloracao_comprido', label: 'Coloração comprido', category: 'Coloração', price: '40€' },
  { id: 'coloracao_total', label: 'Coloração total', category: 'Coloração', price: '48€' },
  { id: 'sem_amoníaco_curto', label: 'Sem amoníaco curto', category: 'Coloração', price: '36€' },
  { id: 'sem_amoníaco_medio', label: 'Sem amoníaco médio', category: 'Coloração', price: '40€' },
  { id: 'sem_amoníaco_comprido', label: 'Sem amoníaco comprido', category: 'Coloração', price: '42€' },
  { id: 'coloracao_vegan', label: 'Coloração vegan', category: 'Coloração', price: '45€' },
  { id: 'descoloracao_total', label: 'Descoloração total', category: 'Coloração', price: '45€' },

  { id: 'madeixas_touca_curto', label: 'Madeixas touca curto', category: 'Madeixas / Forma / Tratamentos', price: '38€' },
  { id: 'madeixas_touca_comprido', label: 'Madeixas touca comprido', category: 'Madeixas / Forma / Tratamentos', price: '48€' },
  { id: 'madeixas_prata_curto', label: 'Madeixas prata/papelote curto', category: 'Madeixas / Forma / Tratamentos', price: '46€' },
  { id: 'madeixas_prata_comprido', label: 'Madeixas prata/papelote comprido', category: 'Madeixas / Forma / Tratamentos', price: '48€' },
  { id: 'permanente_curto', label: 'Permanente curto', category: 'Madeixas / Forma / Tratamentos', price: '38€' },
  { id: 'permanente_comprido', label: 'Permanente comprido', category: 'Madeixas / Forma / Tratamentos', price: '46€' },
  { id: 'desfrisar_curto', label: 'Desfrisar curto', category: 'Madeixas / Forma / Tratamentos', price: '40€' },
  { id: 'desfrisar_comprido', label: 'Desfrisar comprido', category: 'Madeixas / Forma / Tratamentos', price: '48€' },
  { id: 'keratina_medio', label: 'Keratina médio', category: 'Madeixas / Forma / Tratamentos', price: '30€' },
  { id: 'keratina_comprido', label: 'Keratina comprido', category: 'Madeixas / Forma / Tratamentos', price: '40€' },
  { id: 'extensoes', label: 'Extensões', category: 'Madeixas / Forma / Tratamentos', price: '12€' },

  { id: 'manicure', label: 'Manicure', category: 'Unhas / Depilação', price: '6€' },
  { id: 'manicure_verniz_gel', label: 'Manicure verniz gel', category: 'Unhas / Depilação', price: '15€' },
  { id: 'pedicure', label: 'Pedicure', category: 'Unhas / Depilação', price: '17€' },
  { id: 'pedicure_verniz_gel', label: 'Pedicure verniz gel', category: 'Unhas / Depilação', price: '28€' },
  { id: 'verniz_gel_pes', label: 'Aplic. verniz gel pés', category: 'Unhas / Depilação', price: '15€' },
  { id: 'verniz_pes', label: 'Aplic. verniz pés', category: 'Unhas / Depilação', price: '6€' },
  { id: 'perna_inteira', label: 'Perna inteira', category: 'Unhas / Depilação', price: '25€' },
  { id: 'meia_perna', label: 'Meia perna', category: 'Unhas / Depilação', price: '15€' },
  { id: 'axilas', label: 'Axilas', category: 'Unhas / Depilação', price: '10€' },
  { id: 'virilhas', label: 'Virilhas', category: 'Unhas / Depilação', price: '12€' },
  { id: 'bracos', label: 'Braços', category: 'Unhas / Depilação', price: '16€' },
  { id: 'buco', label: 'Buço', category: 'Unhas / Depilação', price: '4,50€' },
  { id: 'rosto', label: 'Rosto', category: 'Unhas / Depilação', price: '8€' },
  { id: 'sobrancelhas', label: 'Sobrancelhas', category: 'Unhas / Depilação', price: '5€' },
  { id: 'sobrancelhas_cera', label: 'Sobrancelhas c/ cera', category: 'Unhas / Depilação', price: '6€' },
] as const

export const SERVICE_CATEGORIES = Array.from(
  new Set(SERVICES.map(s => s.category))
)
